import{a as w,S as v,i}from"./assets/vendor-BjRz3xa9.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function e(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=e(t);fetch(t.href,r)}})();const S="https://pixabay.com/api/",B="49685797-d155f5292c9f3a9a86069a294";async function f(o,n=1){const e={key:B,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:n};try{return(await w.get(S,{params:e})).data}catch(s){throw console.error("Error fetching images:",s),s}}const h=document.querySelector(".gallery"),p=document.querySelector(".loader"),m=document.querySelector(".load-more"),R=new v(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const n=o.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${e.likes}</p>
        <p><b>Views:</b> ${e.views}</p>
        <p><b>Comments:</b> ${e.comments}</p>
        <p><b>Downloads:</b> ${e.downloads}</p>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",n),R.refresh()}function $(){h.innerHTML=""}function y(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function q(){m.classList.remove("hidden")}function E(){m.classList.add("hidden")}let a=1,l="",d=0;const u=document.querySelector(".form"),M=document.querySelector(".load-more");u.addEventListener("submit",async o=>{o.preventDefault();const n=u.elements["search-text"].value.trim();if(!n){i.warning({message:"Please enter a search term",position:"topRight"});return}l=n,a=1,$(),y();try{const e=await f(l,a);e.hits.length===0?i.info({message:"Sorry, no images found.",position:"topRight"}):(g(e.hits),d=e.totalHits,b())}catch{i.error({message:"Error fetching images.",position:"topRight"})}finally{L()}});M.addEventListener("click",async()=>{a+=1,y();try{const o=await f(l,a);g(o.hits),d=o.totalHits,b(),P()}catch{i.error({message:"Error fetching images.",position:"topRight"})}finally{L()}});function b(){galleryContainer.children.length>=d?(E(),i.info({message:"You've reached the end of the results.",position:"topRight"})):q()}function P(){const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
